language: node_js
node_js:
  - "7"
cache: npm
install: npm install --ignore-scripts
script:
  - npm run build
  - npm run test:coverage
notifications:
  email:
  - roxane.mace@amalto.com
after_success: npx codecov --file=./coverage/lcov.info
