language: node_js
node_js:
  - "6"
  - "8"
cache:
  - directories: node_modules
before_install: npm install --global npm@latest
script:
  - npm run test:coverage
  - npm run test:report
after_success: npx nyc report --reporter=text-lcov | npx coveralls
notifications:
  email: "$EMAIL_NOTIFICATION"
